name: Build & (maybe) Publish

on:
  push:
    branches: [ "main" ]        
    tags:     [ "v*", "release-*" ]
  pull_request:                  
    branches: [ "main" ]
  workflow_dispatch:             # test runs
    inputs:
      push_to_registry:
        description: "Actually push to GHCR?"
        type: boolean
        default: false
      name_suffix:
        description: "Optional image suffix for sandbox (e.g. -sandbox)"
        type: string
        default: ""
      extra_tag:
        description: "Optional extra tag (e.g. canary)"
        type: string
        default: ""

permissions:
  contents: read
  packages: write 

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Build (and conditionally push)
        uses: Agile-Software-Engineering-25/build-and-publish-image@v1
        with:
          # Keep defaults unless you need to tweak:
          # image_name: ""           # defaults to repo name (lowercase)
          # context: "."
          # file: "Dockerfile"
          name_suffix: ${{ inputs.name_suffix }}

          # only push when:
          #  - it's a push to main, OR
          #  - it's a tag push, OR
          #  - it's a manual run with push_to_registry=true
          push: ${{ (github.event_name == 'push' && (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/')))
                    || (github.event_name == 'workflow_dispatch' && inputs.push_to_registry) }}

          # add preview tags on PRs or manual runs if you want
          extra_tags: |
            ${{ inputs.extra_tag != '' && format('type=raw,value={0}', inputs.extra_tag) || '' }}
            ${{ github.event_name == 'pull_request' && format('type=raw,value=pr-{0}', github.event.number) || '' }}

          # example: pass build args for Vite base path when testing
          # build_args: |
          #   BASE_PATH=/team/app/my-app/